Update bootstrap/ci behavior

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,58 +1,36 @@
-#!/bin/sh
-#
-# NAME
-#    bootstrap -- initialize/update docker environment
-#
-# SYNOPSIS
-#    bootstrap
-#    bootstrap shellinit
-#
-# DESCRIPTION
-#    Execute this script without parameters to build the local docker
-#    environment.  Once bootstrapped, dependent services are running
-#    via docker-compose and the environment variables are written to
-#    *build/test-environment* for future use.
-#
-#    Running this script with the _shellinit_ command line parameter
-#    causes it to simply interrogate the running docker environment,
-#    update *build/test-environment*, and print the environment to
-#    the standard output stream in a shell executable manner.  This
-#    makes the following pattern for setting environment variables
-#    in the current shell work.
-#
-#        prompt% $(./bootstrap shellinit)
-#
-# vim: set ts=2 sts=2 sw=2 et:
-if test -e /var/run/docker.sock
-then
-  DOCKER_IP=127.0.0.1
-else
-  echo "Failed to initialize docker environment"
-  exit 2
-fi
+#!/usr/bin/env sh
+set -e
+
+# Common constants
+COLOR_RESET='\033[0m'
+COLOR_GREEN='\033[0;32m'
+COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-${PWD##*/}}"
+TEST_HOST="${TEST_HOST:-localhost}"
+
+echo "Integration test host: ${TEST_HOST}"
 
 get_exposed_port() {
-  docker-compose port $1 $2 | cut -d: -f2
+  if [ -z $3 ]
+  then
+    docker-compose port $1 $2 | cut -d: -f2
+  else
+    docker-compose port --index=$3 $1 $2 | cut -d: -f2
+  fi
 }
 
-build_env_file() {
-cat > $1<<EOF
-export DYNAMODB_ENDPOINT=http://${DOCKER_IP}:$(get_exposed_port dynalite 8000)
-export S3_ENDPOINT=http://${DOCKER_IP}:$(get_exposed_port s3 4567)
-EOF
-}
-
-set -e
+# Ensure Docker is Running
+echo "Docker Information:"
+echo ""
+docker version
+echo ""
 
 mkdir -p build
 
-if test "$1" = 'shellinit'
-then
-  # just build the environment file from docker containers
-  build_env_file build/test-environment
-else
-  docker-compose down --volumes --remove-orphans
-  docker-compose up -d
-  build_env_file build/test-environment
-fi
-cat build/test-environment
+# Stop any running instances and clean up after them, then pull images
+docker-compose down --volumes --remove-orphans
+docker-compose up -d --quiet-pull
+
+cat > build/test-environment<<EOF
+export DYNAMODB_ENDPOINT=http://${TEST_HOST}:$(get_exposed_port dynalite 8000)
+export S3_ENDPOINT=http://${TEST_HOST}:$(get_exposed_port s3 4567)
+EOF
